import 'package:drift/drift.dart';

/// Transactions table — stores every UPI payment (sent AND received)
class Transactions extends Table {
  // Primary key — UUID generated by app
  TextColumn get id => text()();

  // Payee details (from QR or manual entry)
  TextColumn get payeeUpiId => text()();
  TextColumn get payeeName => text()();

  // Payment details
  RealColumn get amount => real()();
  TextColumn get currency => text().withDefault(const Constant('INR'))();
  TextColumn get transactionNote => text().nullable()();

  // Transaction tracking
  TextColumn get transactionRef =>
      text()(); // App-generated ref sent to UPI
  TextColumn get upiTxnId =>
      text().nullable()(); // NPCI txn ID from callback
  TextColumn get approvalRefNo =>
      text().nullable()(); // Bank approval ref
  TextColumn get responseCode =>
      text().nullable()(); // UPI response code

  // Status: INITIATED, SUCCESS, FAILURE, SUBMITTED, CANCELLED, ABANDONED
  TextColumn get status =>
      text().withDefault(const Constant('INITIATED'))();

  // How was this payment initiated?
  // QR_SCAN, CONTACT, MANUAL, SMS_IMPORT
  TextColumn get paymentMode => text()();

  // QR type: STATIC, DYNAMIC, or null for contact/manual
  TextColumn get qrType => text().nullable()();

  // Which UPI app was used (package name)
  TextColumn get upiApp => text().nullable()();
  TextColumn get upiAppName => text().nullable()();

  // Expense category
  TextColumn get category =>
      text().withDefault(const Constant('Others'))();

  // Direction: DEBIT (money sent) or CREDIT (money received)
  TextColumn get direction =>
      text().withDefault(const Constant('DEBIT'))();

  // Timestamps
  DateTimeColumn get createdAt =>
      dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedAt =>
      dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}
